version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started...
      - npm run build  # Bỏ qua nếu không có bước build
artifacts:
  files:
    - '**/*'
  base-directory: .